# Variables de entorno de Hyprland.

env = NIXOS_OZONE_WL,1              # Electron/Chromium en Wayland
env = MOZ_ENABLE_WAYLAND,1         # Firefox en Wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = GDK_SCALE,1                  # panel 1080p a escala 1 (evita apps GTK gigantes)

# Cursor Nord (Bibata) para Hyprland/XWayland.
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24

# NVIDIA (aplican cuando la sesión corre sobre la dGPU, p.ej. el perfil 'docked').
# Portadas de tu envs.conf de Omarchy (bloque turing_plus).
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
