# Teclado y touchpad (portado de tu input.conf de Omarchy).
# Docs: https://wiki.hypr.land/Configuring/Variables/#input

input {
  kb_layout = us
  kb_variant = altgr-intl
  kb_options = ctrl:nocaps      # Caps Lock actúa como Ctrl

  repeat_rate = 40
  repeat_delay = 250
  numlock_by_default = true

  touchpad {
    clickfinger_behavior = true # dos dedos = clic derecho
    scroll_factor = 0.4         # velocidad de scroll del touchpad
    natural_scroll = false
  }
}
