return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "css",
      "csv",
      "dockerfile",
      "graphql",
      "html_tags",
      "java",
      "javadoc",
      "javascript",
      "json",
      "latex",
      "lua",
      "markdown",
      "markdown_inline",
      "mermaid",
      "norg",
      "python",
      "rust",
      "scala",
      "scss",
      "sql",
      "svelte",
      "tmux",
      "typescript",
      "typst",
      "vue",
      "xml",
      "yaml",
      "zsh",
    },
  },
}
